### ISSUE TITLE
Not able to compile

### ISSUE THREAD

**Issue by blinkitogaming** [mistergreen/WAAC#22]
Hi there,

I've seen your videos and it looks amazing, such a nice project.

However, I'm not able to compile it.

I'm quite new to arduino. Using Arduino IDE on the latest version and doing all you say at readme file:

1) Files for the html, css, js…at the SD card

2) .ino files at the project folder

3) Library files at the libraries folder inside the project folder.

Logs throw so many errors…

Sure I'm missing something. Any help would be great☺️

thanks!

**Comment by mistergreen** [comment]
Using ESP32?

**Comment by blinkitogaming** [comment]
> Using ESP32?

Yes

**Comment by mistergreen** [comment]
Make sure the libraries are in the library folder in the workspace.
