### ISSUE TITLE
PWM4 does not compile

### ISSUE THREAD

**Issue by LuckyLuzz** [mistergreen/WAAC#8]
Hey, 
just tried to compile your latest code. It doesn't work,  it seams there is a bug in PWM4 lib. 

C:\Users\Thomas\Documents\Arduino\libraries\PWM4\PWM4.cpp:258:0: error: unterminated #else

 #ifdef ESP8266

 ^

C:\Users\Thomas\Documents\Arduino\libraries\PWM4\PWM4.cpp: In member function 'virtual void PWM4::setEvent(char*)':

C:\Users\Thomas\Documents\Arduino\libraries\PWM4\PWM4.cpp:309:5: error: expected '}' at end of input

     }

     ^

Arduino 1.8.5
Master Branch

PS: I did not forget about the hardware :)

**Comment by mistergreen** [comment]
Hey, which folder/hardware are you using?
There's 3
Arduino_Due
ESP32
ESP8266

**Comment by LuckyLuzz** [comment]
ESP32

**Comment by mistergreen** [comment]
Bug fixed. I missed a #endif.

**Comment by LuckyLuzz** [comment]
thanks!
